### ISSUE TITLE
Units of QM9 targets

### ISSUE THREAD

**Issue by dmharoon** [microsoft/tf-gnn-samples#11]
Hi,

Thanks for the code. 
Different papers seem to report different units and there is large difference in the errors of these papers like MPNN and k-gnn ( https://arxiv.org/pdf/1810.02244.pdf ).  Can you let me know what are the units of targets for QM9 dataset reported in the paper?

**Comment by mmjb** [comment]
The paper reports chemical accuracy, as in the Gilmer et al. 2017 paper. This is derived from the mean absolute error (which is reported in the paper you cite), see https://github.com/microsoft/tf-gnn-samples/blob/master/tasks/qm9_task.py#L279

So for example, you can convert the chemical accuracy 2.36 reported in Tab. 2 of https://arxiv.org/pdf/1906.12192.pdf for GNN-MLP0 on task mu into MAE by multiplying with the corresponding factor in https://github.com/microsoft/tf-gnn-samples/blob/master/tasks/qm9_task.py#L22 (the list is in order of the tasks in the table), so this corresponds to a MAE of `2.36 * 0.066513725 = 0.156972391`

**Comment by dmharoon** [comment]
Thanks.
