### ISSUE TITLE
A question about graph generation for dataset

### ISSUE THREAD

**Issue by njuhxc** [microsoft/tf-gnn-samples#15]
Hi, I am trying to understand the "VarMisuse" task and i have run the code successfully. While I am reading dataset of the task, I find the dataset contains pre-generated graphs stored in *.gz from source projects. However, I cannot find code about the graph generation. If it is convenient, could you please tell me is there any code about the preprocessing?
Thanks a lot!

**Comment by mmjb** [comment]
Heya,

The code for the VarMisuse data extraction has sadly not been open-sourced, but a related graph extraction (for a related, but different task) has been released in https://github.com/microsoft/graph-based-code-modelling/.

Marc
