### ISSUE TITLE
Performance issue in the definition of sparse_rgdcn_layer, gnns/rgdcn.py

### ISSUE THREAD

**Issue by DLPerf** [microsoft/tf-gnn-samples#20]
Hello, I found a performance issue in the definition of `sparse_rgdcn_layer`, gnns/rgdcn.py, [tf.initializers.truncated_normal](https://github.com/microsoft/tf-gnn-samples/blob/73e2c950736ac7f662fa88c03c9c0c45fe29d65f/gnns/rgdcn.py#L102)  will created repeatedly during program execution, resulting in reduced efficiency. I think it should be created before the loop in `sparse_rgdcn_layer`.

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by mmjb** [comment]
This is TF1, so this code is building a computation graph that will be re-used. The loop is creating many different weights, and I'm not sure how you are proposing to avoid this?

**Comment by DLPerf** [comment]
I am sorry for that I  propose a wrong issue. I think  tf.initializers.truncated_normal will create repeatedly in the graph by mistake. Thank you for replying me.

**Comment by mmjb** [comment]
It will be called exactly once for each weight that requires initialization, so I think the code is correct.
