### ISSUE TITLE
exception in varmisuse task ,when use no_parallel:bool=True in _load_data() method

### ISSUE THREAD

**Issue by SongXueZhi** [microsoft/tf-gnn-samples#3]
when use params "no_parallel=True" in _load_data() ,We can get the data successfully from load_single_sample method , and reurn result list[GraphSample].but __load_data() can't  get the result from “return _load_data()” ,or the type of the result  that should be a list is a generator.
the code as follow:
![image](https://user-images.githubusercontent.com/28553508/68007524-d4720380-fcb6-11e9-9eed-8036f0c710b6.png)
the exception:
![image](https://user-images.githubusercontent.com/28553508/68007611-1438eb00-fcb7-11e9-8f96-902e5a0868ef.png)
the debug info in vscode:
![image](https://user-images.githubusercontent.com/28553508/68007930-194a6a00-fcb8-11e9-990f-fe31efb3c50e.png)
![image](https://user-images.githubusercontent.com/28553508/68007969-341cde80-fcb8-11e9-9ba8-d33004430538.png)
In order to facilitate debugging, we will assign the result to the temporary variable 'result' first.It is easy to find that there is correct data in ‘result’, but there is no data in self.loaded_data

**Comment by mmjb** [comment]
Sorry for the late reply. This is now fixed in 8732bf2, which makes the parallel and non-parallel versions both use a generator - I haven't really figured out why the existing code didn't work, but I've verified that this new version works fine (for me).
