### ISSUE TITLE
ERRORS: Headers Error for 7za

### ISSUE THREAD

**Issue by redhairdragon** [microsoft/tf-gnn-samples#6]
Hi, when I try to unzip the varmisuse dataset, it says
```

$7za x ../graph-dataset.zip

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,32 CPUs AMD Ryzen Threadripper 2950X 16-Core Processor  (800F82),ASM,AES-NI)

Scanning the drive for archives:
1 file, 14654161628 bytes (14 GiB)

Extracting archive: ../graph-dataset.zip

ERRORS:
Headers Error

--
Path = ../graph-dataset.zip
Type = zip
ERRORS:
Headers Error
Physical Size = 14654161628
64-bit = +



Archives with Errors: 1

Open Errors: 1
```
However, there are still some files get extracted. I wonder if this error is expected?

**Comment by mmjb** [comment]
"Expected" may be the wrong word, but yes, these do occur. Apparently some (minor) header corruption was introduced when archiving the `.zip` or is introduced when downloading it. However, this does not seem to impact the actual data, and so can be safely ignored.
