### ISSUE TITLE
Some questions about running.

### ISSUE THREAD

**Issue by HuantWang** [microsoft/tf-gnn-samples#7]
Hello, I have some questions when running your code:
     For PPI data, I downloaded your ppi.zip, which has .npy file. when Runing code，
ValueError: File suffix must be .json, .json.gz, .pkl or .pkl.gz: data / ppi \ train_feats.npy
How can I fix it ?

**Comment by HuantWang** [comment]
Now, I load it using np.load

**Comment by mmjb** [comment]
I believe the error message here is wrong (it comes from https://github.com/microsoft/dpu-utils/blob/master/python/dpu_utils/utils/richpath.py#L189, but .npy is actually supported in the two lines above).

To debug this further, can you include the exact invocation of `train.py` you tried, show the content of `data/ppi` (either using `ls` or `dir`) and tell me what platform you are using? The `\` in the path looks like you are on Windows? Can you also check what version of `dpu-utils` you have installed (with `pip show dpu-utils`)?

**Comment by HuantWang** [comment]
Thanks for your helping！
When I checked the version of `dpu-utils`, I found that it did not meet the requirements of require.txt. After Updating the version and then solve the problem. I debug under windows, thank you very much for your help!
