### ISSUE TITLE
varmisuse_data_splitter

### ISSUE THREAD

**Issue by xxrz** [microsoft/tf-gnn-samples#8]
Hi,Good evening~
I am confused about using reorg_varmisuse_data file and I need your help.
I know that when this file runs to the end, the varmisuse_data_splitter.py file is not executed,
The error is as follows：
“
File "./utils/varmisuse_data_splitter.py", line 26
    def _data_loading_worker(file_queue:Queue, result_queue:Queue) -> None:
                                       ^
SyntaxError: invalid syntax
”
I tried to solve this problem, but it didn't work.If you can provide some help, thank you so much!!!!

**Comment by mmjb** [comment]
This looks like your `python` executable still points to the deprecated and outdated Python 2. You should be able to fix the issue by changing the call in `reorg_varmisuse_data.sh` to use `python3` explicitly. I've just pushed that change, and you should be able to run things using the updated codebase.

**Comment by xxrz** [comment]
Thank you very much for solving my problem in time. good luck~
